-- Create table

  CREATE TABLE BOOKS_COLLECTIONS 
   (	IDBOOK integer, 
	IDCOLLECTION integer, 
	INSERTED timestamp DEFAULT systimestamp NOT NULL , 
	MODIFIED timestamp DEFAULT systimestamp NOT NULL , 
	 CONSTRAINT PK_BOOKS_COLLECTIONS PRIMARY KEY (IDBOOK, IDCOLLECTION) , 
	 CONSTRAINT FK_BOOKS_COLLECTIONSCOLLECTION FOREIGN KEY (IDCOLLECTION)
	  REFERENCES COLLECTIONS (IDCOLLECTION) ON DELETE CASCADE , 
	 CONSTRAINT FK_BOOKS_COLLECTIONS_IDBOOK FOREIGN KEY (IDBOOK)
	  REFERENCES BOOKS (IDBOOK) ON DELETE CASCADE 
   ) ;

-- Add comments to the columns
comment on column BOOKS_COLLECTIONS.INSERTED
is 'Дата вставки записи';
comment on column BOOKS_COLLECTIONS.MODIFIED
is 'Дата последнего изменения записи';
-- Create/Recreate indexes

  CREATE INDEX FK_BOOKS_COLLECTIONSCOLLECTION ON BOOKS_COLLECTIONS (IDCOLLECTION) 
  ;


  CREATE UNIQUE INDEX PK_BOOKS_COLLECTIONS ON BOOKS_COLLECTIONS (IDBOOK, IDCOLLECTION) 
  ;

